### ISSUE TITLE
More bugs when trying to do examples

### ISSUE THREAD

**Issue by JamesSuter** [UCL-CCS/FabMD#4] opened 2019-06-11 16:01 UTC
I'm trying to work through the examples on the EasyVVUQ + FabMD

I tried to run the example using localhost. 

I found that, no matter what I specified on the command line, the settings in FabMD/default_settings/lammps.yaml took precedence. I wanted to run on only one core, but fab localhost easymd_example:fabmd_easyvvuq,cores=1,wall_time=1:00:0 still ran on 24 cores (the value in default_settings/lammps.yaml)

Also, it is not clear that config_dir is a place holder for a general directory name. A user might type in in "config_dir" thinking this is required.

**Comment by JamesSuter** [comment] 2019-06-11 16:07
Also, the files are not in FabMD/config_files/fabmd_easyvvuq but plugins/FabMD/config_files/fabmd_easyvvuq , assuming that FabSim is your base directory. 

Also typo: "pnadas dataframse"

**Comment by djgroen** [comment] 2019-06-11 21:39
Okay, I fixed all the minor issues.

**Comment by djgroen** [comment] 2019-06-12 04:59
Okay, going through the big issue now:
"I found that, no matter what I specified on the command line, the settings in FabMD/default_settings/lammps.yaml took precedence. I wanted to run on only one core, but fab localhost easymd_example:fabmd_easyvvuq,cores=1,wall_time=1:00:0 still ran on 24 cores (the value in default_settings/lammps.yaml)"

For `lammps_ensemble` this works as it should (cmd line args override defaults), but for easymd_example this was indeed broken, because the arguments were not passed on to the ensemble command.

I believe I have fixed this now. @JamesSuter, would you  be willing to give the command above a quick test today?

**Comment by djgroen** [comment] 2019-06-12 05:05
I tested it on eagle myself now, and it works as intended now for me. It'd be good for you to double-check it though, particularly because I don't have lammps set up on eagle yet (I only see that the job definitions are correct).

**Comment by JamesSuter** [comment] 2019-06-12 10:08
@djgroen It does work now
However, when I updated FabMD using "fabsim localhost install_plugin:FabMD", it wiped everything in the plugins/FabMD directory, including default_settings/lammps.yaml etc etc, and all previous inputs / runs (which were created in the config_files directory). Is this expected behaviour? Some warning should be given.

**Comment by JamesSuter** [comment] 2019-06-12 10:08
Perhaps there is a way to update the plugin, rather than reinstall?

**Comment by djgroen** [comment] 2019-06-12 10:22
@JamesSuter That is a very good point. I believe this is possible and will look into it.

**Comment by djgroen** [comment] 2019-06-12 10:28
@JamesSuter I made an update_plugin function now. Could you pull the latest version of FabSim3 and try it using
`fabsim localhost update_plugin:FabMD` ?

**Comment by JamesSuter** [comment] 2019-06-12 10:36
It worked, although, of course, I got a "Already up to date." message

**Comment by djgroen** [comment] 2019-06-12 10:39
Well, that makes sense :). I guess we managed to solve the issues in this ticket then, so are you okay if I close it?

**Comment by JamesSuter** [comment] 2019-06-12 10:42
close away

**Closed** 2019-06-12 10:42 UTC
Labels: bug
